on: [push]
name: Frontend_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Stap 1: GitHub-repository ophalen
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    # Stap 2: Inloggen via Azure CLI
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Stap 3: Inloggen bij Azure Container Registry
    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Stap 4: Bouw de container en push naar ACR
    - run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }} ./frontend
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}

    # Stap 5: Deploy de container naar Azure Container Instances (ACI)
    - name: 'Deploy to Azure Container Instances'
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: aci-frontend
        location: 'northeurope'
        environment-variables: |
          FRONTEND_ENV=${{ secrets.FRONTEND_ENV }}